#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

feh --bg-fill personal/wallpapers/ghibli.jpg

# Kill any existing polybar instances (hot reload safe)
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done
polybar default &