#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config remove_unplugged_monitors true

if [[ $(xrandr -q | grep "HDMI-0 connected") ]]; then
    # HDMI-0 is connected
    xrandr \
        --output DP-0 --primary --mode 3840x2160 --rate 120.00 --pos 0x0 --rotate normal \
        --output HDMI-0 --mode 1920x1080 --pos 3840x626 --rotate normal

    bspc monitor DP-0 -d I II III IV V
    bspc monitor HDMI-0 -d VI VII VIII IX X
else
    # Only DP-0 is connected
    xrandr \
        --output DP-0 --primary --mode 3840x2160 --rate 120.00 --pos 0x0 --rotate normal \
        --output HDMI-0 --off

    bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         1
bspc config window_gap          1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

feh --bg-fill personal/wallpapers/ghibli.jpg

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload default &
  done
else
  polybar --reload default &
fi